// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// QueryObjectByVersionID provides a mock function with given fields: versionid
func (_m *Service) QueryObjectByVersionID(versionid []byte) ([]byte, error) {
	ret := _m.Called(versionid)

	var r0 []byte
	if rf, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = rf(versionid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(versionid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
