// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Server) Close() {
	_m.Called()
}

// Publish provides a mock function with given fields: objectID, labels, success
func (_m *Server) Publish(objectID []byte, labels []string, success bool) {
	_m.Called(objectID, labels, success)
}
