#! /usr/bin/env bash

if (( $# != 1 )); then
    echo "missing filename";
    exit 1;
fi

proto_ext=.proto

# Generate the Go code for the given protobuf definition.
protoc -I=. -I=${GOPATH}/src --gogo_out=plugins=:. ${1}

# Strip the autogenerated package doc.
content=$(cat ${1%$proto_ext}.pb.go | awk '/^package/ { found = 1 } found { print }')

# Add back the prelude to the generated file.
echo -e "// Code generated by protoc-gen-gogo. DO NOT EDIT.\n// source: types.proto\n\n${content}" > ${1%$proto_ext}.pb.go
