// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package broadcast

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OP int32

const (
	OP_UNKNOWN        OP = 0
	OP_BLOCK_LIST     OP = 1
	OP_BROADCAST_ACK  OP = 2
	OP_BROADCAST_LIST OP = 3
	OP_GET_BLOCKS     OP = 4
	OP_GET_ROUNDS     OP = 5
)

var OP_name = map[int32]string{
	0: "UNKNOWN",
	1: "BLOCK_LIST",
	2: "BROADCAST_ACK",
	3: "BROADCAST_LIST",
	4: "GET_BLOCKS",
	5: "GET_ROUNDS",
}
var OP_value = map[string]int32{
	"UNKNOWN":        0,
	"BLOCK_LIST":     1,
	"BROADCAST_ACK":  2,
	"BROADCAST_LIST": 3,
	"GET_BLOCKS":     4,
	"GET_ROUNDS":     5,
}

func (x OP) String() string {
	return proto.EnumName(OP_name, int32(x))
}
func (OP) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

type Block struct {
	Node         uint64             `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Previous     []byte             `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	References   []*SignedData      `protobuf:"bytes,3,rep,name=references" json:"references,omitempty"`
	Round        uint64             `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Transactions []*TransactionData `protobuf:"bytes,5,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *Block) GetNode() uint64 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *Block) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Block) GetReferences() []*SignedData {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Block) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Block) GetTransactions() []*TransactionData {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockList struct {
	Blocks []*SignedData `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *BlockList) Reset()                    { *m = BlockList{} }
func (m *BlockList) String() string            { return proto.CompactTextString(m) }
func (*BlockList) ProtoMessage()               {}
func (*BlockList) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *BlockList) GetBlocks() []*SignedData {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BlockReference struct {
	Hash  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Node  uint64 `protobuf:"varint,2,opt,name=node,proto3" json:"node,omitempty"`
	Round uint64 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *BlockReference) Reset()                    { *m = BlockReference{} }
func (m *BlockReference) String() string            { return proto.CompactTextString(m) }
func (*BlockReference) ProtoMessage()               {}
func (*BlockReference) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *BlockReference) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockReference) GetNode() uint64 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *BlockReference) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type BroadcastAck struct {
	Last uint64 `protobuf:"varint,1,opt,name=last,proto3" json:"last,omitempty"`
}

func (m *BroadcastAck) Reset()                    { *m = BroadcastAck{} }
func (m *BroadcastAck) String() string            { return proto.CompactTextString(m) }
func (*BroadcastAck) ProtoMessage()               {}
func (*BroadcastAck) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

func (m *BroadcastAck) GetLast() uint64 {
	if m != nil {
		return m.Last
	}
	return 0
}

type GetBlocks struct {
	Blocks []*BlockReference `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *GetBlocks) Reset()                    { *m = GetBlocks{} }
func (m *GetBlocks) String() string            { return proto.CompactTextString(m) }
func (*GetBlocks) ProtoMessage()               {}
func (*GetBlocks) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *GetBlocks) GetBlocks() []*BlockReference {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type GetRounds struct {
	Rounds []uint64 `protobuf:"varint,1,rep,packed,name=rounds" json:"rounds,omitempty"`
}

func (m *GetRounds) Reset()                    { *m = GetRounds{} }
func (m *GetRounds) String() string            { return proto.CompactTextString(m) }
func (*GetRounds) ProtoMessage()               {}
func (*GetRounds) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *GetRounds) GetRounds() []uint64 {
	if m != nil {
		return m.Rounds
	}
	return nil
}

type SignedData struct {
	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SignedData) Reset()                    { *m = SignedData{} }
func (m *SignedData) String() string            { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()               {}
func (*SignedData) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{6} }

func (m *SignedData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TransactionData struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Fee  uint64 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *TransactionData) Reset()                    { *m = TransactionData{} }
func (m *TransactionData) String() string            { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()               {}
func (*TransactionData) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{7} }

func (m *TransactionData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionData) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "broadcast.Block")
	proto.RegisterType((*BlockList)(nil), "broadcast.BlockList")
	proto.RegisterType((*BlockReference)(nil), "broadcast.BlockReference")
	proto.RegisterType((*BroadcastAck)(nil), "broadcast.BroadcastAck")
	proto.RegisterType((*GetBlocks)(nil), "broadcast.GetBlocks")
	proto.RegisterType((*GetRounds)(nil), "broadcast.GetRounds")
	proto.RegisterType((*SignedData)(nil), "broadcast.SignedData")
	proto.RegisterType((*TransactionData)(nil), "broadcast.TransactionData")
	proto.RegisterEnum("broadcast.OP", OP_name, OP_value)
}

func init() { proto.RegisterFile("broadcast/types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x8b, 0xd3, 0x50,
	0x10, 0x35, 0x4d, 0x5a, 0xed, 0x6c, 0xad, 0x71, 0x70, 0x25, 0x16, 0x1f, 0x4a, 0x7c, 0x29, 0xc2,
	0xb6, 0xa8, 0x88, 0xe0, 0x43, 0xa1, 0x1f, 0xb2, 0x48, 0x4b, 0x22, 0x37, 0x5d, 0x7c, 0x2c, 0x37,
	0xc9, 0x6d, 0x1a, 0x5c, 0x73, 0x4b, 0xee, 0x8d, 0xe0, 0xff, 0xf3, 0x87, 0x49, 0xa6, 0x4d, 0x9a,
	0x2d, 0xe2, 0xdb, 0x39, 0x93, 0x39, 0x33, 0x67, 0x4e, 0x2e, 0x5c, 0x87, 0xb9, 0xe4, 0x71, 0xc4,
	0x95, 0x9e, 0xe8, 0xdf, 0x07, 0xa1, 0xc6, 0x87, 0x5c, 0x6a, 0x89, 0xdd, 0xba, 0x3c, 0xb8, 0x49,
	0x52, 0xbd, 0x2f, 0xc2, 0x71, 0x24, 0x7f, 0x4e, 0x12, 0x99, 0xc8, 0x09, 0x75, 0x84, 0xc5, 0x8e,
	0x18, 0x11, 0x42, 0x47, 0xa5, 0xfb, 0xc7, 0x80, 0xf6, 0xfc, 0x5e, 0x46, 0x3f, 0x10, 0xc1, 0xca,
	0x64, 0x2c, 0x1c, 0x63, 0x68, 0x8c, 0x2c, 0x46, 0x18, 0x07, 0xf0, 0xe4, 0x90, 0x8b, 0x5f, 0xa9,
	0x2c, 0x94, 0xd3, 0x1a, 0x1a, 0xa3, 0x1e, 0xab, 0x39, 0x7e, 0x04, 0xc8, 0xc5, 0x4e, 0xe4, 0x22,
	0x8b, 0x84, 0x72, 0xcc, 0xa1, 0x39, 0xba, 0x7a, 0x7f, 0x3d, 0xae, 0x8d, 0x8c, 0x83, 0x34, 0xc9,
	0x44, 0xbc, 0xe4, 0x9a, 0xb3, 0x46, 0x23, 0xbe, 0x80, 0x76, 0x2e, 0x8b, 0x2c, 0x76, 0x2c, 0xda,
	0x73, 0x24, 0x38, 0x85, 0x9e, 0xce, 0x79, 0xa6, 0x78, 0xa4, 0x53, 0x99, 0x29, 0xa7, 0x4d, 0xe3,
	0x06, 0x8d, 0x71, 0x9b, 0xf3, 0x67, 0x9a, 0xf9, 0xa0, 0xdf, 0xfd, 0x0c, 0x5d, 0xba, 0x62, 0x9d,
	0x2a, 0x8d, 0x37, 0xd0, 0x09, 0x4b, 0xa2, 0x1c, 0xe3, 0x7f, 0xae, 0x4e, 0x4d, 0xae, 0x07, 0x7d,
	0xd2, 0xb2, 0xca, 0x64, 0x19, 0xc5, 0x9e, 0xab, 0x3d, 0x45, 0xd1, 0x63, 0x84, 0xeb, 0x78, 0x5a,
	0x8d, 0x78, 0xea, 0x5b, 0xcc, 0xc6, 0x2d, 0xae, 0x0b, 0xbd, 0x79, 0xb5, 0x6f, 0x76, 0x0c, 0xf6,
	0x9e, 0x2b, 0x5d, 0x05, 0x5b, 0x62, 0x77, 0x0a, 0xdd, 0x5b, 0xa1, 0x69, 0xad, 0xc2, 0x77, 0x17,
	0x7e, 0x5f, 0x35, 0xfc, 0x3e, 0x74, 0x56, 0x7b, 0x7e, 0x43, 0x7a, 0x56, 0xee, 0x53, 0xf8, 0x12,
	0x3a, 0xb4, 0xf9, 0xa8, 0xb7, 0xd8, 0x89, 0xb9, 0x53, 0x80, 0xf3, 0xb9, 0xa5, 0x8d, 0x98, 0x6b,
	0x5e, 0x1d, 0x55, 0x62, 0x7c, 0x0d, 0x5d, 0x95, 0x26, 0x19, 0xd7, 0x45, 0x2e, 0x4e, 0x3f, 0xf8,
	0x5c, 0x70, 0x3f, 0xc1, 0xb3, 0x8b, 0xd4, 0xff, 0x39, 0xc4, 0x06, 0x73, 0x27, 0xaa, 0x60, 0x4a,
	0xf8, 0x76, 0x0f, 0x2d, 0xff, 0x1b, 0x5e, 0xc1, 0xe3, 0x3b, 0x6f, 0xe5, 0xf9, 0xdf, 0x3d, 0xfb,
	0x11, 0xf6, 0x01, 0xe6, 0x6b, 0x7f, 0xb1, 0xda, 0xae, 0xbf, 0x06, 0x1b, 0xdb, 0xc0, 0xe7, 0xf0,
	0x74, 0xce, 0xfc, 0xd9, 0x72, 0x31, 0x0b, 0x36, 0xdb, 0xd9, 0x62, 0x65, 0xb7, 0x10, 0xa1, 0x7f,
	0x2e, 0x51, 0x9b, 0x59, 0xca, 0x6e, 0xbf, 0x6c, 0xb6, 0x24, 0x0d, 0x6c, 0xab, 0xe2, 0xcc, 0xbf,
	0xf3, 0x96, 0x81, 0xdd, 0x0e, 0x3b, 0xf4, 0x8a, 0x3f, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x98,
	0xc7, 0x31, 0x48, 0x18, 0x03, 0x00, 0x00,
}
