// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package broadcast

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OP int32

const (
	OP_UNKNOWN    OP = 0
	OP_BLOCK_LIST OP = 1
	OP_GET_BLOCKS OP = 2
	OP_GET_HASHES OP = 3
	OP_HASH_LIST  OP = 4
)

var OP_name = map[int32]string{
	0: "UNKNOWN",
	1: "BLOCK_LIST",
	2: "GET_BLOCKS",
	3: "GET_HASHES",
	4: "HASH_LIST",
}
var OP_value = map[string]int32{
	"UNKNOWN":    0,
	"BLOCK_LIST": 1,
	"GET_BLOCKS": 2,
	"GET_HASHES": 3,
	"HASH_LIST":  4,
}

func (x OP) String() string {
	return proto.EnumName(OP_name, int32(x))
}
func (OP) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

type Block struct {
	Node         uint64             `protobuf:"varint,1,opt,name=node,proto3" json:"node,omitempty"`
	Previous     []byte             `protobuf:"bytes,2,opt,name=previous,proto3" json:"previous,omitempty"`
	References   []*BlockReference  `protobuf:"bytes,3,rep,name=references" json:"references,omitempty"`
	Round        uint64             `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Transactions []*TransactionData `protobuf:"bytes,5,rep,name=transactions" json:"transactions,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *Block) GetNode() uint64 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *Block) GetPrevious() []byte {
	if m != nil {
		return m.Previous
	}
	return nil
}

func (m *Block) GetReferences() []*BlockReference {
	if m != nil {
		return m.References
	}
	return nil
}

func (m *Block) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

func (m *Block) GetTransactions() []*TransactionData {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockList struct {
	Blocks []*SignedData `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *BlockList) Reset()                    { *m = BlockList{} }
func (m *BlockList) String() string            { return proto.CompactTextString(m) }
func (*BlockList) ProtoMessage()               {}
func (*BlockList) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *BlockList) GetBlocks() []*SignedData {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BlockReference struct {
	Hash  []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Node  uint64 `protobuf:"varint,2,opt,name=node,proto3" json:"node,omitempty"`
	Round uint64 `protobuf:"varint,3,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *BlockReference) Reset()                    { *m = BlockReference{} }
func (m *BlockReference) String() string            { return proto.CompactTextString(m) }
func (*BlockReference) ProtoMessage()               {}
func (*BlockReference) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *BlockReference) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockReference) GetNode() uint64 {
	if m != nil {
		return m.Node
	}
	return 0
}

func (m *BlockReference) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

type GetBlocks struct {
	Blocks []*BlockReference `protobuf:"bytes,1,rep,name=blocks" json:"blocks,omitempty"`
}

func (m *GetBlocks) Reset()                    { *m = GetBlocks{} }
func (m *GetBlocks) String() string            { return proto.CompactTextString(m) }
func (*GetBlocks) ProtoMessage()               {}
func (*GetBlocks) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

func (m *GetBlocks) GetBlocks() []*BlockReference {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type GetHashes struct {
	Since uint64 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
}

func (m *GetHashes) Reset()                    { *m = GetHashes{} }
func (m *GetHashes) String() string            { return proto.CompactTextString(m) }
func (*GetHashes) ProtoMessage()               {}
func (*GetHashes) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *GetHashes) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

type HashList struct {
	Hashes [][]byte `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
	Latest uint64   `protobuf:"varint,2,opt,name=latest,proto3" json:"latest,omitempty"`
	Since  uint64   `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
}

func (m *HashList) Reset()                    { *m = HashList{} }
func (m *HashList) String() string            { return proto.CompactTextString(m) }
func (*HashList) ProtoMessage()               {}
func (*HashList) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *HashList) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *HashList) GetLatest() uint64 {
	if m != nil {
		return m.Latest
	}
	return 0
}

func (m *HashList) GetSince() uint64 {
	if m != nil {
		return m.Since
	}
	return 0
}

type SignedData struct {
	Data      []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SignedData) Reset()                    { *m = SignedData{} }
func (m *SignedData) String() string            { return proto.CompactTextString(m) }
func (*SignedData) ProtoMessage()               {}
func (*SignedData) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{6} }

func (m *SignedData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SignedData) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type TransactionData struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Fee  uint64 `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
}

func (m *TransactionData) Reset()                    { *m = TransactionData{} }
func (m *TransactionData) String() string            { return proto.CompactTextString(m) }
func (*TransactionData) ProtoMessage()               {}
func (*TransactionData) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{7} }

func (m *TransactionData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionData) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "broadcast.Block")
	proto.RegisterType((*BlockList)(nil), "broadcast.BlockList")
	proto.RegisterType((*BlockReference)(nil), "broadcast.BlockReference")
	proto.RegisterType((*GetBlocks)(nil), "broadcast.GetBlocks")
	proto.RegisterType((*GetHashes)(nil), "broadcast.GetHashes")
	proto.RegisterType((*HashList)(nil), "broadcast.HashList")
	proto.RegisterType((*SignedData)(nil), "broadcast.SignedData")
	proto.RegisterType((*TransactionData)(nil), "broadcast.TransactionData")
	proto.RegisterEnum("broadcast.OP", OP_name, OP_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x25, 0x4d, 0x5b, 0x96, 0xdb, 0x32, 0x22, 0x0b, 0x50, 0xa8, 0x78, 0x28, 0x79, 0xaa, 0x90,
	0xd6, 0x09, 0x78, 0x40, 0xf0, 0x50, 0x89, 0xc1, 0xb4, 0xa2, 0x55, 0x69, 0x95, 0x14, 0xf1, 0x38,
	0x39, 0x89, 0x9b, 0x44, 0x0c, 0xbb, 0xb2, 0x1d, 0x24, 0xfe, 0x21, 0x3f, 0x0b, 0xf9, 0xe6, 0x73,
	0x13, 0xda, 0xdb, 0x39, 0xd7, 0xc7, 0xe7, 0xde, 0x7b, 0x6c, 0x98, 0xe8, 0x3f, 0x47, 0xa6, 0x96,
	0x47, 0x29, 0xb4, 0x20, 0x4e, 0x2c, 0x05, 0x4d, 0x13, 0xaa, 0xf4, 0xec, 0x2c, 0x2b, 0x74, 0x5e,
	0xc6, 0xcb, 0x44, 0xfc, 0x3a, 0xcf, 0x44, 0x26, 0xce, 0x51, 0x11, 0x97, 0x07, 0x64, 0x48, 0x10,
	0x55, 0x37, 0xfd, 0xbf, 0x16, 0x8c, 0x2e, 0x6e, 0x45, 0xf2, 0x93, 0x10, 0x18, 0x72, 0x91, 0x32,
	0xcf, 0x9a, 0x5b, 0x8b, 0x61, 0x88, 0x98, 0xcc, 0xe0, 0xe4, 0x28, 0xd9, 0xef, 0x42, 0x94, 0xca,
	0x1b, 0xcc, 0xad, 0xc5, 0x34, 0x6c, 0x39, 0xf9, 0x08, 0x20, 0xd9, 0x81, 0x49, 0xc6, 0x13, 0xa6,
	0x3c, 0x7b, 0x6e, 0x2f, 0x26, 0xef, 0x5e, 0x2e, 0xdb, 0x41, 0x96, 0xe8, 0x1a, 0x36, 0x8a, 0xb0,
	0x27, 0x26, 0xcf, 0x60, 0x24, 0x45, 0xc9, 0x53, 0x6f, 0x88, 0xbd, 0x2a, 0x42, 0x56, 0x30, 0xd5,
	0x92, 0x72, 0x45, 0x13, 0x5d, 0x08, 0xae, 0xbc, 0x11, 0x5a, 0xce, 0x7a, 0x96, 0xfb, 0xee, 0xf8,
	0x2b, 0xd5, 0x34, 0xbc, 0xa3, 0xf7, 0x3f, 0x81, 0x83, 0x3d, 0x37, 0x85, 0xd2, 0xe4, 0x0c, 0xc6,
	0xb1, 0x21, 0xca, 0xb3, 0xd0, 0xe6, 0x79, 0xcf, 0x26, 0x2a, 0x32, 0xce, 0x52, 0x74, 0xa8, 0x45,
	0x7e, 0x00, 0xa7, 0x77, 0xe7, 0x35, 0x71, 0xe4, 0x54, 0xe5, 0x18, 0xc7, 0x34, 0x44, 0xdc, 0x46,
	0x34, 0xe8, 0x45, 0xd4, 0xee, 0x62, 0xf7, 0x76, 0xf1, 0x57, 0xe0, 0x5c, 0x31, 0x8d, 0x96, 0x8a,
	0xbc, 0xbd, 0x37, 0xcb, 0x03, 0x29, 0x35, 0xf3, 0xbc, 0xc6, 0xfb, 0x6b, 0xaa, 0xf2, 0x2a, 0x2e,
	0x55, 0xf0, 0xa4, 0x79, 0x9a, 0x8a, 0xf8, 0x3b, 0x38, 0x31, 0xe7, 0xb8, 0xed, 0x0b, 0x18, 0xe7,
	0xa8, 0xc5, 0x0e, 0xd3, 0xb0, 0x66, 0xa6, 0x7e, 0x4b, 0x35, 0x53, 0xba, 0x1e, 0xb9, 0x66, 0x9d,
	0xa3, 0xdd, 0x77, 0x5c, 0x01, 0x74, 0xd1, 0x98, 0x65, 0x53, 0xaa, 0x69, 0x13, 0x80, 0xc1, 0xe4,
	0x15, 0x38, 0xaa, 0xc8, 0x38, 0xd5, 0xa5, 0x64, 0xf5, 0x87, 0xe8, 0x0a, 0xfe, 0x07, 0x78, 0x7a,
	0xef, 0x85, 0xfe, 0x6b, 0xe2, 0x82, 0x7d, 0x60, 0x4d, 0x88, 0x06, 0xbe, 0xd9, 0xc1, 0x60, 0xbb,
	0x23, 0x13, 0x78, 0xfc, 0x3d, 0xb8, 0x0e, 0xb6, 0x3f, 0x02, 0xf7, 0x11, 0x39, 0x05, 0xb8, 0xd8,
	0x6c, 0xbf, 0x5c, 0xdf, 0x6c, 0xbe, 0x45, 0x7b, 0xd7, 0x32, 0xfc, 0xea, 0x72, 0x7f, 0x83, 0xb5,
	0xc8, 0x1d, 0x34, 0x7c, 0xfd, 0x39, 0x5a, 0x5f, 0x46, 0xae, 0x4d, 0x9e, 0x80, 0x63, 0x70, 0x25,
	0x1f, 0xc6, 0x63, 0xfc, 0xdd, 0xef, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x69, 0xd7, 0x37,
	0x26, 0x03, 0x00, 0x00,
}
