#! /usr/bin/env bash

# Generate the Go code for the given protobuf definition.
protoc -I=. -I=${GOPATH}/src --gogo_out=plugins=:. types.proto

# Strip the autogenerated package doc.
content=$(cat types.pb.go | awk '/^package/ { found = 1 } found { print }')

# Add back the prelude to the generated file.
echo -e "// Code generated by protoc-gen-gogo. DO NOT EDIT.\n// source: types.proto\n\n${content}" > types.pb.go
