// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import conns "chainspace.io/chainspace-go/internal/conns"
import mock "github.com/stretchr/testify/mock"

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

// Borrow provides a mock function with given fields:
func (_m *Pool) Borrow() conns.Cache {
	ret := _m.Called()

	var r0 conns.Cache
	if rf, ok := ret.Get(0).(func() conns.Cache); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conns.Cache)
		}
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *Pool) Close() {
	_m.Called()
}

// MessageAckPending provides a mock function with given fields:
func (_m *Pool) MessageAckPending() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
