// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "chainspace.io/prototype/pubsub/api"
import internal "chainspace.io/prototype/pubsub/internal"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Callback provides a mock function with given fields: p
func (_m *Service) Callback(p internal.Payload) {
	_m.Called(p)
}

// Websocket provides a mock function with given fields: _a0, _a1
func (_m *Service) Websocket(_a0 string, _a1 api.WriteMessageCloser) (int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, api.WriteMessageCloser) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, api.WriteMessageCloser) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
