// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-17 11:10:12.324589 +0000 GMT m=+0.111040701

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Transfer funds from a wallet to another",
        "title": "cs-coin API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/checker/check": {
            "post": {
                "description": "Checks something",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "checker"
                ],
                "summary": "Checks something",
                "operationId": "check",
                "parameters": [
                    {
                        "description": "transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.CheckTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/cs-coin/wallet": {
            "post": {
                "description": "Create a new Wallet from address generated by the user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cs-coin-methods"
                ],
                "summary": "Create a new Wallet from address generated by the user",
                "operationId": "createWallet",
                "parameters": [
                    {
                        "description": "wallet",
                        "name": "wallet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.CreateWalletRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/cs-coin/wallet/add-funds": {
            "post": {
                "description": "Add new funds to user wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cs-coin-methods"
                ],
                "summary": "Add new funds to a user wallet",
                "operationId": "addFunds",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.AddFundsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/cs-coin/wallet/init/{addr}": {
            "get": {
                "description": "Generate the seed object for a new wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cs-coin-init"
                ],
                "summary": "Generate the seed object for a new wallet",
                "operationId": "init",
                "parameters": [
                    {
                        "type": "string",
                        "description": "addr",
                        "name": "addr",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.InitResponse"
                        }
                    }
                }
            }
        },
        "/api/cs-coin/wallet/transfer-funds": {
            "post": {
                "description": "Transfer funds from a wallet to another",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cs-coin-methods"
                ],
                "summary": "Transfer funds from a wallet to another",
                "operationId": "transferFunds",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.TransferFundsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/kv/label/{label}": {
            "get": {
                "description": "get string by label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "Retrieve a key by its label",
                "operationId": "getbyLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/kv/label/{label}/version-id": {
            "get": {
                "description": "get version ID by label",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "Retrieve a version ID by its label",
                "operationId": "getVersionIDbyLabel",
                "parameters": [
                    {
                        "type": "string",
                        "description": "label",
                        "name": "label",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.VersionIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/kv/prefix/{prefix}": {
            "get": {
                "description": "See before",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "See before",
                "operationId": "getByPrefix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "prefix",
                        "name": "prefix",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ListObjectsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/kv/prefix/{prefix}/version-id": {
            "get": {
                "description": "see before",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "See before",
                "operationId": "getVersionIDbyPrefix",
                "parameters": [
                    {
                        "type": "string",
                        "description": "prefix",
                        "name": "prefix",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ListVersionIDsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/pubsub/ws": {
            "get": {
                "description": "Iniate a websocket connection",
                "tags": [
                    "pubsub"
                ],
                "summary": "Initiate a websocket connection in order to subscribed to object saved in chainspace by the current node",
                "operationId": "websocket",
                "responses": {
                    "204": {},
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/sbac/object": {
            "post": {
                "description": "TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sbac"
                ],
                "summary": "Create an object to a shard",
                "operationId": "createObject",
                "parameters": [
                    {
                        "description": "object",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ObjectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.ObjectIDResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/sbac/states": {
            "get": {
                "description": "TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sbac"
                ],
                "summary": "Get the states",
                "operationId": "states",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/sbac/transaction": {
            "post": {
                "description": "TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sbac"
                ],
                "summary": "Add a transaction to a shard",
                "operationId": "addTransaction",
                "parameters": [
                    {
                        "description": "transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        },
        "/api/sbac/transaction-checked": {
            "post": {
                "description": "TODO",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sbac"
                ],
                "summary": "Add a transaction which is already checked to a shard",
                "operationId": "addTransaction",
                "parameters": [
                    {
                        "description": "transaction",
                        "name": "transaction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Transaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/api.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AddFundsRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "mappings": {
                    "type": "object"
                },
                "signature": {
                    "type": "string"
                },
                "wallet": {
                    "type": "string"
                }
            }
        },
        "api.CheckTransactionResponse": {
            "type": "object",
            "properties": {
                "nodeId": {
                    "type": "integer"
                },
                "ok": {
                    "type": "boolean"
                },
                "signature": {
                    "type": "string"
                }
            }
        },
        "api.CreateWalletRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "initObject": {
                    "type": "string"
                },
                "mappings": {
                    "type": "object"
                },
                "pubKey": {
                    "type": "string"
                }
            }
        },
        "api.Dependency": {},
        "api.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api.InitResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "initObject": {
                    "type": "string"
                }
            }
        },
        "api.LabelObject": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "object": {
                    "type": "object"
                }
            }
        },
        "api.LabelVersionID": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "api.ListObjectsResponse": {
            "type": "object",
            "properties": {
                "pairs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LabelObject"
                    }
                }
            }
        },
        "api.ListVersionIDsResponse": {
            "type": "object",
            "properties": {
                "pairs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.LabelVersionID"
                    }
                }
            }
        },
        "api.Object": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                },
                "value": {
                    "type": "object"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "api.ObjectIDResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "api.ObjectRequest": {
            "type": "object",
            "properties": {
                "object": {
                    "type": "object"
                }
            }
        },
        "api.ObjectResponse": {
            "type": "object",
            "properties": {
                "object": {
                    "type": "object"
                }
            }
        },
        "api.OutputObject": {
            "type": "object",
            "properties": {
                "labels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "object": {
                    "type": "string"
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "transaction": {
                    "type": "string"
                }
            }
        },
        "api.Trace": {
            "type": "object",
            "properties": {
                "contractId": {
                    "type": "string"
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Dependency"
                    }
                },
                "inputObjectVersionIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "inputReferenceVersionIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outputObjects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.OutputObject"
                    }
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "procedure": {
                    "type": "string"
                },
                "returns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.Transaction": {
            "type": "object",
            "properties": {
                "mappings": {
                    "type": "object"
                },
                "signatures": {
                    "type": "object"
                },
                "traces": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.Trace"
                    }
                }
            }
        },
        "api.TransferFundsRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "fromWallet": {
                    "type": "string"
                },
                "mappings": {
                    "type": "object"
                },
                "signature": {
                    "type": "string"
                },
                "toWallet": {
                    "type": "string"
                }
            }
        },
        "api.VersionIDResponse": {
            "type": "object",
            "properties": {
                "versionId": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
