#! /usr/bin/env bash

if (( $# != 1 )); then
    echo "Usage: run-testnet NETWORK_NAME";
    exit 1;
fi

echo ">> Building chainspace"
go install chainspace.io/prototype/cmd/chainspace

session="run-${1}"

echo ">> Setting up tmux session"
tmux new-session -d -s $session
tmux select-window -t $session:0
tmux send-keys "chainspace run ${1} 1" "C-l" "C-m"
tmux split-window -h
tmux send-keys "chainspace run ${1} 4" "C-l" "C-m"
tmux split-window -v -t 0
tmux send-keys "chainspace run ${1} 7" "C-l" "C-m"
tmux split-window -v -t 2
tmux send-keys "chainspace run ${1} 10" "C-l" "C-m"
tmux attach-session -t $session
