#!/usr/bin/env bash

if (( $# != 1 )); then
    echo "Usage: runcheckersharding NUMBEROFNODES";
    exit 1;
fi

session=checker-sharding-gcp-$1
#zones=("asia-east1-b" "europe-west2-b" "northamerica-northeast1-b" "us-west2-b")
zones=("europe-west2-a")

echo ">> Setting up tmux session ${session}"
tmux new-session -d -s ${session}

for i in $(seq 1 $1)
do
    #im=`expr $i - 1`
    #ii=`expr $im % 4`
    #zone=${zones[${ii}]}
    tmux send-keys "gcloud compute  ssh --zone \"europe-west2-a\" \"checker-node-sharding-${i}\"" "C-l" "C-m"
    tmux send-keys "/etc/chainspace/runcheckersharding.sh" "C-l" "C-m"


    if (( $i != $1 )); then
	tmux split-window
	tmux select-layout tiled
    fi
done

tmux attach-session -t $session
