// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package transactor

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Opcode int32

const (
	Opcode_UNKNOWN           Opcode = 0
	Opcode_CHECK_TRANSACTION Opcode = 1
	Opcode_ADD_TRANSACTION   Opcode = 2
	Opcode_QUERY_OBJECT      Opcode = 3
	Opcode_CREATE_OBJECT     Opcode = 4
	Opcode_DELETE_OBJECT     Opcode = 5
	Opcode_SBAC              Opcode = 6
)

var Opcode_name = map[int32]string{
	0: "UNKNOWN",
	1: "CHECK_TRANSACTION",
	2: "ADD_TRANSACTION",
	3: "QUERY_OBJECT",
	4: "CREATE_OBJECT",
	5: "DELETE_OBJECT",
	6: "SBAC",
}
var Opcode_value = map[string]int32{
	"UNKNOWN":           0,
	"CHECK_TRANSACTION": 1,
	"ADD_TRANSACTION":   2,
	"QUERY_OBJECT":      3,
	"CREATE_OBJECT":     4,
	"DELETE_OBJECT":     5,
	"SBAC":              6,
}

func (x Opcode) String() string {
	return proto.EnumName(Opcode_name, int32(x))
}
func (Opcode) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

type ObjectStatus int32

const (
	ObjectStatus_ACTIVE   ObjectStatus = 0
	ObjectStatus_INACTIVE ObjectStatus = 1
	ObjectStatus_LOCKED   ObjectStatus = 2
)

var ObjectStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "LOCKED",
}
var ObjectStatus_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"LOCKED":   2,
}

func (x ObjectStatus) String() string {
	return proto.EnumName(ObjectStatus_name, int32(x))
}
func (ObjectStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

type Transaction struct {
	Traces []*Trace `protobuf:"bytes,1,rep,name=traces" json:"traces,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *Transaction) GetTraces() []*Trace {
	if m != nil {
		return m.Traces
	}
	return nil
}

type Trace struct {
	ContractID          string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Procedure           string   `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	InputObjectsKeys    [][]byte `protobuf:"bytes,3,rep,name=inputObjectsKeys" json:"inputObjectsKeys,omitempty"`
	InputReferencesKeys [][]byte `protobuf:"bytes,4,rep,name=inputReferencesKeys" json:"inputReferencesKeys,omitempty"`
	OutputObjects       [][]byte `protobuf:"bytes,5,rep,name=outputObjects" json:"outputObjects,omitempty"`
	Parameters          [][]byte `protobuf:"bytes,6,rep,name=parameters" json:"parameters,omitempty"`
	Returns             [][]byte `protobuf:"bytes,7,rep,name=returns" json:"returns,omitempty"`
	Dependencies        []*Trace `protobuf:"bytes,8,rep,name=dependencies" json:"dependencies,omitempty"`
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *Trace) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *Trace) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *Trace) GetInputObjectsKeys() [][]byte {
	if m != nil {
		return m.InputObjectsKeys
	}
	return nil
}

func (m *Trace) GetInputReferencesKeys() [][]byte {
	if m != nil {
		return m.InputReferencesKeys
	}
	return nil
}

func (m *Trace) GetOutputObjects() [][]byte {
	if m != nil {
		return m.OutputObjects
	}
	return nil
}

func (m *Trace) GetParameters() [][]byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Trace) GetReturns() [][]byte {
	if m != nil {
		return m.Returns
	}
	return nil
}

func (m *Trace) GetDependencies() []*Trace {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type Object struct {
	Value  []byte       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Key    []byte       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Status ObjectStatus `protobuf:"varint,3,opt,name=status,proto3,enum=transactor.ObjectStatus" json:"status,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *Object) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Object) GetStatus() ObjectStatus {
	if m != nil {
		return m.Status
	}
	return ObjectStatus_ACTIVE
}

type CheckTransactionRequest struct {
	Tx *Transaction `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
}

func (m *CheckTransactionRequest) Reset()                    { *m = CheckTransactionRequest{} }
func (m *CheckTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckTransactionRequest) ProtoMessage()               {}
func (*CheckTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

func (m *CheckTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type CheckTransactionResponse struct {
	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *CheckTransactionResponse) Reset()                    { *m = CheckTransactionResponse{} }
func (m *CheckTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckTransactionResponse) ProtoMessage()               {}
func (*CheckTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *CheckTransactionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CheckTransactionResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AddTransactionRequest struct {
	Tx        *Transaction      `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	Evidences map[uint64][]byte `protobuf:"bytes,2,rep,name=evidences" json:"evidences,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *AddTransactionRequest) Reset()                    { *m = AddTransactionRequest{} }
func (m *AddTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTransactionRequest) ProtoMessage()               {}
func (*AddTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *AddTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *AddTransactionRequest) GetEvidences() map[uint64][]byte {
	if m != nil {
		return m.Evidences
	}
	return nil
}

type ObjectTraceIDPair struct {
	TraceID []byte    `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	Objects []*Object `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (m *ObjectTraceIDPair) Reset()                    { *m = ObjectTraceIDPair{} }
func (m *ObjectTraceIDPair) String() string            { return proto.CompactTextString(m) }
func (*ObjectTraceIDPair) ProtoMessage()               {}
func (*ObjectTraceIDPair) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{6} }

func (m *ObjectTraceIDPair) GetTraceID() []byte {
	if m != nil {
		return m.TraceID
	}
	return nil
}

func (m *ObjectTraceIDPair) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

type ObjectList struct {
	List []*Object `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ObjectList) Reset()                    { *m = ObjectList{} }
func (m *ObjectList) String() string            { return proto.CompactTextString(m) }
func (*ObjectList) ProtoMessage()               {}
func (*ObjectList) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{7} }

func (m *ObjectList) GetList() []*Object {
	if m != nil {
		return m.List
	}
	return nil
}

type AddTransactionResponse struct {
	Objects map[string]*ObjectList `protobuf:"bytes,1,rep,name=objects" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AddTransactionResponse) Reset()                    { *m = AddTransactionResponse{} }
func (m *AddTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*AddTransactionResponse) ProtoMessage()               {}
func (*AddTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{8} }

func (m *AddTransactionResponse) GetObjects() map[string]*ObjectList {
	if m != nil {
		return m.Objects
	}
	return nil
}

type QueryObjectRequest struct {
	ObjectKey []byte `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
}

func (m *QueryObjectRequest) Reset()                    { *m = QueryObjectRequest{} }
func (m *QueryObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectRequest) ProtoMessage()               {}
func (*QueryObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{9} }

func (m *QueryObjectRequest) GetObjectKey() []byte {
	if m != nil {
		return m.ObjectKey
	}
	return nil
}

type QueryObjectResponse struct {
	Object *Object `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
}

func (m *QueryObjectResponse) Reset()                    { *m = QueryObjectResponse{} }
func (m *QueryObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectResponse) ProtoMessage()               {}
func (*QueryObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{10} }

func (m *QueryObjectResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type DeleteObjectRequest struct {
	ObjectKey []byte `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
}

func (m *DeleteObjectRequest) Reset()                    { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()               {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{11} }

func (m *DeleteObjectRequest) GetObjectKey() []byte {
	if m != nil {
		return m.ObjectKey
	}
	return nil
}

type DeleteObjectResponse struct {
	Object *Object `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
}

func (m *DeleteObjectResponse) Reset()                    { *m = DeleteObjectResponse{} }
func (m *DeleteObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteObjectResponse) ProtoMessage()               {}
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{12} }

func (m *DeleteObjectResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

type NewObjectRequest struct {
	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (m *NewObjectRequest) Reset()                    { *m = NewObjectRequest{} }
func (m *NewObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*NewObjectRequest) ProtoMessage()               {}
func (*NewObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{13} }

func (m *NewObjectRequest) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

type NewObjectResponse struct {
	ID []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *NewObjectResponse) Reset()                    { *m = NewObjectResponse{} }
func (m *NewObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*NewObjectResponse) ProtoMessage()               {}
func (*NewObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{14} }

func (m *NewObjectResponse) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transactor.Transaction")
	proto.RegisterType((*Trace)(nil), "transactor.Trace")
	proto.RegisterType((*Object)(nil), "transactor.Object")
	proto.RegisterType((*CheckTransactionRequest)(nil), "transactor.CheckTransactionRequest")
	proto.RegisterType((*CheckTransactionResponse)(nil), "transactor.CheckTransactionResponse")
	proto.RegisterType((*AddTransactionRequest)(nil), "transactor.AddTransactionRequest")
	proto.RegisterType((*ObjectTraceIDPair)(nil), "transactor.ObjectTraceIDPair")
	proto.RegisterType((*ObjectList)(nil), "transactor.ObjectList")
	proto.RegisterType((*AddTransactionResponse)(nil), "transactor.AddTransactionResponse")
	proto.RegisterType((*QueryObjectRequest)(nil), "transactor.QueryObjectRequest")
	proto.RegisterType((*QueryObjectResponse)(nil), "transactor.QueryObjectResponse")
	proto.RegisterType((*DeleteObjectRequest)(nil), "transactor.DeleteObjectRequest")
	proto.RegisterType((*DeleteObjectResponse)(nil), "transactor.DeleteObjectResponse")
	proto.RegisterType((*NewObjectRequest)(nil), "transactor.NewObjectRequest")
	proto.RegisterType((*NewObjectResponse)(nil), "transactor.NewObjectResponse")
	proto.RegisterEnum("transactor.Opcode", Opcode_name, Opcode_value)
	proto.RegisterEnum("transactor.ObjectStatus", ObjectStatus_name, ObjectStatus_value)
}

func init() { proto.RegisterFile("service/transactor/types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 813 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x0d, 0x29, 0x99, 0xb2, 0x46, 0x8c, 0x4b, 0xad, 0x13, 0x87, 0x30, 0x82, 0xd8, 0x20, 0xfa,
	0xe1, 0xaa, 0xa9, 0x64, 0x28, 0x29, 0x10, 0x14, 0xbd, 0x48, 0x14, 0x81, 0xa8, 0x32, 0xa4, 0x66,
	0xad, 0xb4, 0xe8, 0x29, 0xa0, 0xc8, 0x89, 0xcd, 0xda, 0x21, 0x55, 0xee, 0xd2, 0x8d, 0xce, 0xfd,
	0x51, 0xfd, 0x0f, 0x3d, 0xf4, 0x27, 0xf8, 0xe0, 0x5f, 0x52, 0x70, 0x77, 0x69, 0x52, 0xb1, 0x5a,
	0xa0, 0xcd, 0x8d, 0xf3, 0xe6, 0xcd, 0x9b, 0xdd, 0xf7, 0xd6, 0x16, 0x3c, 0x61, 0x98, 0x5e, 0x45,
	0x01, 0xf6, 0x78, 0xea, 0xc7, 0xcc, 0x0f, 0x78, 0x92, 0xf6, 0xf8, 0x6a, 0x89, 0xac, 0xbb, 0x4c,
	0x13, 0x9e, 0x10, 0x28, 0xf1, 0xfd, 0xaf, 0xcf, 0x22, 0x7e, 0x9e, 0x2d, 0xba, 0x41, 0xf2, 0xae,
	0x77, 0x96, 0x9c, 0x25, 0x3d, 0x41, 0x59, 0x64, 0x6f, 0x45, 0x25, 0x0a, 0xf1, 0x25, 0x47, 0x9d,
	0x17, 0xd0, 0x9a, 0xab, 0xe1, 0x28, 0x89, 0xc9, 0x97, 0x60, 0xf0, 0xd4, 0x0f, 0x90, 0xd9, 0xda,
	0x61, 0xed, 0xa8, 0xd5, 0x6f, 0x77, 0x4b, 0xe9, 0xee, 0x3c, 0xef, 0x50, 0x45, 0x70, 0xfe, 0xd4,
	0x61, 0x4b, 0x20, 0xa4, 0x0b, 0x10, 0x24, 0x71, 0x0e, 0xf3, 0xf1, 0xc8, 0xd6, 0x0e, 0xb5, 0xa3,
	0xe6, 0x70, 0xe7, 0xe6, 0xfa, 0x00, 0xdc, 0x5b, 0x94, 0x56, 0x18, 0xe4, 0x31, 0x34, 0x97, 0x69,
	0x12, 0x60, 0x98, 0xa5, 0x68, 0xeb, 0x39, 0x9d, 0x96, 0x00, 0xe9, 0x80, 0x15, 0xc5, 0xcb, 0x8c,
	0xcf, 0x16, 0xbf, 0x60, 0xc0, 0xd9, 0x04, 0x57, 0xcc, 0xae, 0x1d, 0xd6, 0x8e, 0x4c, 0x7a, 0x07,
	0x27, 0xc7, 0xb0, 0x2b, 0x30, 0x8a, 0x6f, 0x31, 0xc5, 0x38, 0x40, 0x49, 0xaf, 0x0b, 0xfa, 0xa6,
	0x16, 0xf9, 0x14, 0xee, 0x27, 0x19, 0x2f, 0x65, 0xec, 0x2d, 0xc1, 0x5d, 0x07, 0xc9, 0x13, 0x80,
	0xa5, 0x9f, 0xfa, 0xef, 0x90, 0x63, 0xca, 0x6c, 0x43, 0x50, 0x2a, 0x08, 0xb1, 0xa1, 0x91, 0x22,
	0xcf, 0xd2, 0x98, 0xd9, 0x0d, 0xd1, 0x2c, 0x4a, 0xf2, 0x0d, 0x98, 0x21, 0x2e, 0x31, 0x0e, 0x31,
	0x0e, 0x22, 0x64, 0xf6, 0xf6, 0x3f, 0xd9, 0xb8, 0x46, 0x73, 0x16, 0x60, 0xc8, 0xdd, 0xe4, 0x01,
	0x6c, 0x5d, 0xf9, 0x97, 0x19, 0x0a, 0x1f, 0x4d, 0x2a, 0x0b, 0x62, 0x41, 0xed, 0x02, 0x57, 0xc2,
	0x2c, 0x93, 0xe6, 0x9f, 0xe4, 0x18, 0x0c, 0xc6, 0x7d, 0x9e, 0xe5, 0xe6, 0x68, 0x47, 0x3b, 0x7d,
	0xbb, 0xba, 0x42, 0x6a, 0x9d, 0x8a, 0x3e, 0x55, 0x3c, 0x67, 0x08, 0x8f, 0xdc, 0x73, 0x0c, 0x2e,
	0x2a, 0x79, 0x53, 0xfc, 0x35, 0x43, 0xc6, 0xc9, 0x17, 0xa0, 0xf3, 0xf7, 0x62, 0x63, 0xab, 0xff,
	0xe8, 0x83, 0xb3, 0xde, 0x72, 0x75, 0xfe, 0xde, 0x79, 0x09, 0xf6, 0x5d, 0x0d, 0xb6, 0x4c, 0x62,
	0x86, 0x64, 0x07, 0xf4, 0xe4, 0x42, 0x88, 0x6c, 0x53, 0x3d, 0xb9, 0xc8, 0x63, 0x66, 0xd1, 0x59,
	0xec, 0xf3, 0x22, 0x66, 0x93, 0x96, 0x80, 0xf3, 0x97, 0x06, 0x0f, 0x07, 0x61, 0xf8, 0x11, 0x87,
	0x21, 0x53, 0x68, 0xe2, 0x55, 0x14, 0x8a, 0x70, 0x6d, 0x5d, 0x18, 0x7d, 0x5c, 0xe5, 0x6f, 0x94,
	0xef, 0x7a, 0xc5, 0x88, 0x17, 0xf3, 0x74, 0x45, 0x4b, 0x89, 0xfd, 0xef, 0x60, 0x67, 0xbd, 0x59,
	0xd8, 0x9e, 0x9f, 0xa5, 0x2e, 0x6d, 0xbf, 0x8d, 0x47, 0xaf, 0xc4, 0xf3, 0xad, 0xfe, 0x42, 0x73,
	0xce, 0xa1, 0x2d, 0x6d, 0x17, 0xf9, 0x8e, 0x47, 0x3f, 0xf8, 0x51, 0x4a, 0x3e, 0x83, 0x06, 0x97,
	0xa5, 0xcc, 0x73, 0xd8, 0xba, 0xb9, 0x3e, 0x68, 0x28, 0x06, 0x2d, 0x7a, 0xe4, 0x29, 0x34, 0x12,
	0xf5, 0x1e, 0xe5, 0x3d, 0xc8, 0xdd, 0x34, 0x69, 0x41, 0x71, 0x9e, 0x03, 0x48, 0xe8, 0x24, 0x62,
	0x9c, 0x7c, 0x0e, 0xf5, 0xcb, 0x88, 0x71, 0xf5, 0x07, 0xbb, 0x69, 0x50, 0xf4, 0x9d, 0x3f, 0x34,
	0xd8, 0xfb, 0xd0, 0x11, 0x95, 0xdc, 0xb8, 0x5c, 0x2f, 0x55, 0x7a, 0xff, 0x66, 0xa3, 0x1c, 0x52,
	0xe2, 0xca, 0xc5, 0x62, 0x7e, 0x9f, 0x82, 0x59, 0x6d, 0x54, 0x1d, 0x6c, 0x4a, 0x07, 0x9f, 0x56,
	0x1d, 0x6c, 0xf5, 0xf7, 0xee, 0x1e, 0x38, 0xbf, 0x56, 0xd5, 0xd9, 0x3e, 0x90, 0x57, 0x19, 0xa6,
	0x2b, 0x75, 0x1d, 0xf5, 0x4c, 0x1e, 0x43, 0x53, 0x2e, 0x9d, 0x28, 0x7d, 0x93, 0x96, 0x80, 0x33,
	0x80, 0xdd, 0xb5, 0x19, 0x75, 0xd3, 0x0e, 0x18, 0x92, 0xa3, 0xde, 0xd7, 0x26, 0xbb, 0x14, 0xc3,
	0x79, 0x06, 0xbb, 0x23, 0xbc, 0x44, 0x8e, 0xff, 0x65, 0xef, 0x10, 0x1e, 0xac, 0x0f, 0xfd, 0x8f,
	0xc5, 0x1d, 0xb0, 0xa6, 0xf8, 0xdb, 0xfa, 0xd6, 0xbd, 0xb5, 0x79, 0xf3, 0x96, 0xfb, 0x15, 0xb4,
	0x2b, 0x5c, 0xb5, 0x6c, 0x0f, 0xf4, 0x28, 0x54, 0x0f, 0xce, 0xb8, 0xb9, 0x3e, 0xd0, 0xc7, 0x23,
	0xaa, 0x47, 0x61, 0xe7, 0x77, 0x0d, 0x8c, 0xd9, 0x32, 0x48, 0x42, 0x24, 0x2d, 0x68, 0xbc, 0x9e,
	0x4e, 0xa6, 0xb3, 0x9f, 0xa6, 0xd6, 0x3d, 0xf2, 0x10, 0xda, 0xee, 0x4b, 0xcf, 0x9d, 0xbc, 0x99,
	0xd3, 0xc1, 0xf4, 0x74, 0xe0, 0xce, 0xc7, 0xb3, 0xa9, 0xa5, 0x91, 0x5d, 0xf8, 0x64, 0x30, 0x1a,
	0xad, 0x81, 0x3a, 0xb1, 0xc0, 0x7c, 0xf5, 0xda, 0xa3, 0x3f, 0xbf, 0x99, 0x0d, 0xbf, 0xf7, 0xdc,
	0xb9, 0x55, 0x23, 0x6d, 0xb8, 0xef, 0x52, 0x6f, 0x30, 0xf7, 0x0a, 0xa8, 0x9e, 0x43, 0x23, 0xef,
	0xc4, 0x2b, 0xa1, 0x2d, 0xb2, 0x0d, 0xf5, 0xd3, 0xe1, 0xc0, 0xb5, 0x8c, 0xce, 0xf3, 0xe2, 0x89,
	0xc8, 0xff, 0x4f, 0x04, 0xc0, 0xc8, 0xd5, 0x7f, 0xf4, 0xac, 0x7b, 0xc4, 0x84, 0xed, 0xf1, 0x54,
	0x55, 0x5a, 0xde, 0x39, 0x99, 0xb9, 0x13, 0x6f, 0x64, 0xe9, 0x0b, 0x43, 0xfc, 0x5e, 0x3d, 0xfb,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x30, 0x98, 0x97, 0x0c, 0x07, 0x00, 0x00,
}
