// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package transactor

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Opcode int32

const (
	Opcode_UNKNOWN           Opcode = 0
	Opcode_CHECK_TRANSACTION Opcode = 1
	Opcode_ADD_TRANSACTION   Opcode = 2
	Opcode_QUERY_OBJECT      Opcode = 3
	Opcode_CREATE_OBJECT     Opcode = 4
	Opcode_DELETE_OBJECT     Opcode = 5
	Opcode_STATES            Opcode = 6
	Opcode_SBAC              Opcode = 7
)

var Opcode_name = map[int32]string{
	0: "UNKNOWN",
	1: "CHECK_TRANSACTION",
	2: "ADD_TRANSACTION",
	3: "QUERY_OBJECT",
	4: "CREATE_OBJECT",
	5: "DELETE_OBJECT",
	6: "STATES",
	7: "SBAC",
}
var Opcode_value = map[string]int32{
	"UNKNOWN":           0,
	"CHECK_TRANSACTION": 1,
	"ADD_TRANSACTION":   2,
	"QUERY_OBJECT":      3,
	"CREATE_OBJECT":     4,
	"DELETE_OBJECT":     5,
	"STATES":            6,
	"SBAC":              7,
}

func (x Opcode) String() string {
	return proto.EnumName(Opcode_name, int32(x))
}
func (Opcode) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

type ObjectStatus int32

const (
	ObjectStatus_ACTIVE   ObjectStatus = 0
	ObjectStatus_INACTIVE ObjectStatus = 1
	ObjectStatus_LOCKED   ObjectStatus = 2
)

var ObjectStatus_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
	2: "LOCKED",
}
var ObjectStatus_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
	"LOCKED":   2,
}

func (x ObjectStatus) String() string {
	return proto.EnumName(ObjectStatus_name, int32(x))
}
func (ObjectStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

type SBACOpcode int32

const (
	SBACOpcode_CONSENSUS1       SBACOpcode = 0
	SBACOpcode_CONSENSUS2       SBACOpcode = 1
	SBACOpcode_PHASE1           SBACOpcode = 2
	SBACOpcode_PHASE2           SBACOpcode = 3
	SBACOpcode_COMMIT           SBACOpcode = 4
	SBACOpcode_CONSENSUS_COMMIT SBACOpcode = 5
)

var SBACOpcode_name = map[int32]string{
	0: "CONSENSUS1",
	1: "CONSENSUS2",
	2: "PHASE1",
	3: "PHASE2",
	4: "COMMIT",
	5: "CONSENSUS_COMMIT",
}
var SBACOpcode_value = map[string]int32{
	"CONSENSUS1":       0,
	"CONSENSUS2":       1,
	"PHASE1":           2,
	"PHASE2":           3,
	"COMMIT":           4,
	"CONSENSUS_COMMIT": 5,
}

func (x SBACOpcode) String() string {
	return proto.EnumName(SBACOpcode_name, int32(x))
}
func (SBACOpcode) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

type SBACDecision int32

const (
	SBACDecision_ACCEPT SBACDecision = 0
	SBACDecision_REJECT SBACDecision = 1
)

var SBACDecision_name = map[int32]string{
	0: "ACCEPT",
	1: "REJECT",
}
var SBACDecision_value = map[string]int32{
	"ACCEPT": 0,
	"REJECT": 1,
}

func (x SBACDecision) String() string {
	return proto.EnumName(SBACDecision_name, int32(x))
}
func (SBACDecision) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

type Transaction struct {
	Traces []*Trace `protobuf:"bytes,1,rep,name=traces" json:"traces,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *Transaction) GetTraces() []*Trace {
	if m != nil {
		return m.Traces
	}
	return nil
}

type Strings struct {
	Strs []string `protobuf:"bytes,1,rep,name=strs" json:"strs,omitempty"`
}

func (m *Strings) Reset()                    { *m = Strings{} }
func (m *Strings) String() string            { return proto.CompactTextString(m) }
func (*Strings) ProtoMessage()               {}
func (*Strings) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *Strings) GetStrs() []string {
	if m != nil {
		return m.Strs
	}
	return nil
}

type Trace struct {
	ContractID          string     `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Procedure           string     `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	InputObjectsKeys    [][]byte   `protobuf:"bytes,3,rep,name=inputObjectsKeys" json:"inputObjectsKeys,omitempty"`
	InputReferencesKeys [][]byte   `protobuf:"bytes,4,rep,name=inputReferencesKeys" json:"inputReferencesKeys,omitempty"`
	OutputObjects       [][]byte   `protobuf:"bytes,5,rep,name=outputObjects" json:"outputObjects,omitempty"`
	Parameters          [][]byte   `protobuf:"bytes,6,rep,name=parameters" json:"parameters,omitempty"`
	Returns             [][]byte   `protobuf:"bytes,7,rep,name=returns" json:"returns,omitempty"`
	Labels              []*Strings `protobuf:"bytes,8,rep,name=labels" json:"labels,omitempty"`
	Dependencies        []*Trace   `protobuf:"bytes,9,rep,name=dependencies" json:"dependencies,omitempty"`
	InputObjects        [][]byte   `protobuf:"bytes,10,rep,name=inputObjects" json:"inputObjects,omitempty"`
	InputReferences     [][]byte   `protobuf:"bytes,11,rep,name=inputReferences" json:"inputReferences,omitempty"`
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *Trace) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *Trace) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *Trace) GetInputObjectsKeys() [][]byte {
	if m != nil {
		return m.InputObjectsKeys
	}
	return nil
}

func (m *Trace) GetInputReferencesKeys() [][]byte {
	if m != nil {
		return m.InputReferencesKeys
	}
	return nil
}

func (m *Trace) GetOutputObjects() [][]byte {
	if m != nil {
		return m.OutputObjects
	}
	return nil
}

func (m *Trace) GetParameters() [][]byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Trace) GetReturns() [][]byte {
	if m != nil {
		return m.Returns
	}
	return nil
}

func (m *Trace) GetLabels() []*Strings {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Trace) GetDependencies() []*Trace {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Trace) GetInputObjects() [][]byte {
	if m != nil {
		return m.InputObjects
	}
	return nil
}

func (m *Trace) GetInputReferences() [][]byte {
	if m != nil {
		return m.InputReferences
	}
	return nil
}

type Object struct {
	Value  []byte       `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Key    []byte       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Status ObjectStatus `protobuf:"varint,3,opt,name=status,proto3,enum=transactor.ObjectStatus" json:"status,omitempty"`
	Labels []string     `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

func (m *Object) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Object) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Object) GetStatus() ObjectStatus {
	if m != nil {
		return m.Status
	}
	return ObjectStatus_ACTIVE
}

func (m *Object) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type CheckTransactionRequest struct {
	Tx *Transaction `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
}

func (m *CheckTransactionRequest) Reset()                    { *m = CheckTransactionRequest{} }
func (m *CheckTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*CheckTransactionRequest) ProtoMessage()               {}
func (*CheckTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *CheckTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

type CheckTransactionResponse struct {
	Ok        bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *CheckTransactionResponse) Reset()                    { *m = CheckTransactionResponse{} }
func (m *CheckTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*CheckTransactionResponse) ProtoMessage()               {}
func (*CheckTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *CheckTransactionResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func (m *CheckTransactionResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type AddTransactionRequest struct {
	Tx        *Transaction      `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	Evidences map[uint64][]byte `protobuf:"bytes,2,rep,name=evidences" json:"evidences,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *AddTransactionRequest) Reset()                    { *m = AddTransactionRequest{} }
func (m *AddTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*AddTransactionRequest) ProtoMessage()               {}
func (*AddTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{6} }

func (m *AddTransactionRequest) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *AddTransactionRequest) GetEvidences() map[uint64][]byte {
	if m != nil {
		return m.Evidences
	}
	return nil
}

type ObjectTraceIDPair struct {
	TraceID []byte    `protobuf:"bytes,1,opt,name=traceID,proto3" json:"traceID,omitempty"`
	Objects []*Object `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
}

func (m *ObjectTraceIDPair) Reset()                    { *m = ObjectTraceIDPair{} }
func (m *ObjectTraceIDPair) String() string            { return proto.CompactTextString(m) }
func (*ObjectTraceIDPair) ProtoMessage()               {}
func (*ObjectTraceIDPair) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{7} }

func (m *ObjectTraceIDPair) GetTraceID() []byte {
	if m != nil {
		return m.TraceID
	}
	return nil
}

func (m *ObjectTraceIDPair) GetObjects() []*Object {
	if m != nil {
		return m.Objects
	}
	return nil
}

type ObjectList struct {
	List []*Object `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ObjectList) Reset()                    { *m = ObjectList{} }
func (m *ObjectList) String() string            { return proto.CompactTextString(m) }
func (*ObjectList) ProtoMessage()               {}
func (*ObjectList) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{8} }

func (m *ObjectList) GetList() []*Object {
	if m != nil {
		return m.List
	}
	return nil
}

type AddTransactionResponse struct {
	Objects map[string]*ObjectList `protobuf:"bytes,1,rep,name=objects" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AddTransactionResponse) Reset()                    { *m = AddTransactionResponse{} }
func (m *AddTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*AddTransactionResponse) ProtoMessage()               {}
func (*AddTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{9} }

func (m *AddTransactionResponse) GetObjects() map[string]*ObjectList {
	if m != nil {
		return m.Objects
	}
	return nil
}

type StateReport struct {
	HashID          uint32          `protobuf:"varint,1,opt,name=hashID,proto3" json:"hashID,omitempty"`
	CommitDecisions map[uint64]bool `protobuf:"bytes,2,rep,name=commitDecisions" json:"commitDecisions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Phase1Decisions map[uint64]bool `protobuf:"bytes,3,rep,name=phase1Decisions" json:"phase1Decisions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Phase2Decisions map[uint64]bool `protobuf:"bytes,4,rep,name=phase2Decisions" json:"phase2Decisions,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	State           string          `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	PendingEvents   int32           `protobuf:"varint,6,opt,name=pendingEvents,proto3" json:"pendingEvents,omitempty"`
}

func (m *StateReport) Reset()                    { *m = StateReport{} }
func (m *StateReport) String() string            { return proto.CompactTextString(m) }
func (*StateReport) ProtoMessage()               {}
func (*StateReport) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{10} }

func (m *StateReport) GetHashID() uint32 {
	if m != nil {
		return m.HashID
	}
	return 0
}

func (m *StateReport) GetCommitDecisions() map[uint64]bool {
	if m != nil {
		return m.CommitDecisions
	}
	return nil
}

func (m *StateReport) GetPhase1Decisions() map[uint64]bool {
	if m != nil {
		return m.Phase1Decisions
	}
	return nil
}

func (m *StateReport) GetPhase2Decisions() map[uint64]bool {
	if m != nil {
		return m.Phase2Decisions
	}
	return nil
}

func (m *StateReport) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StateReport) GetPendingEvents() int32 {
	if m != nil {
		return m.PendingEvents
	}
	return 0
}

type StatesReportResponse struct {
	States        []*StateReport `protobuf:"bytes,1,rep,name=states" json:"states,omitempty"`
	EventsInQueue int32          `protobuf:"varint,2,opt,name=eventsInQueue,proto3" json:"eventsInQueue,omitempty"`
}

func (m *StatesReportResponse) Reset()                    { *m = StatesReportResponse{} }
func (m *StatesReportResponse) String() string            { return proto.CompactTextString(m) }
func (*StatesReportResponse) ProtoMessage()               {}
func (*StatesReportResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{11} }

func (m *StatesReportResponse) GetStates() []*StateReport {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *StatesReportResponse) GetEventsInQueue() int32 {
	if m != nil {
		return m.EventsInQueue
	}
	return 0
}

type QueryObjectRequest struct {
	ObjectKey []byte `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
}

func (m *QueryObjectRequest) Reset()                    { *m = QueryObjectRequest{} }
func (m *QueryObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectRequest) ProtoMessage()               {}
func (*QueryObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{12} }

func (m *QueryObjectRequest) GetObjectKey() []byte {
	if m != nil {
		return m.ObjectKey
	}
	return nil
}

type QueryObjectResponse struct {
	Object *Object `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	Error  string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *QueryObjectResponse) Reset()                    { *m = QueryObjectResponse{} }
func (m *QueryObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryObjectResponse) ProtoMessage()               {}
func (*QueryObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{13} }

func (m *QueryObjectResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *QueryObjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type DeleteObjectRequest struct {
	ObjectKey []byte `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
}

func (m *DeleteObjectRequest) Reset()                    { *m = DeleteObjectRequest{} }
func (m *DeleteObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteObjectRequest) ProtoMessage()               {}
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{14} }

func (m *DeleteObjectRequest) GetObjectKey() []byte {
	if m != nil {
		return m.ObjectKey
	}
	return nil
}

type DeleteObjectResponse struct {
	Object *Object `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
	Error  string  `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *DeleteObjectResponse) Reset()                    { *m = DeleteObjectResponse{} }
func (m *DeleteObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteObjectResponse) ProtoMessage()               {}
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{15} }

func (m *DeleteObjectResponse) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func (m *DeleteObjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type NewObjectRequest struct {
	Object []byte `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
}

func (m *NewObjectRequest) Reset()                    { *m = NewObjectRequest{} }
func (m *NewObjectRequest) String() string            { return proto.CompactTextString(m) }
func (*NewObjectRequest) ProtoMessage()               {}
func (*NewObjectRequest) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{16} }

func (m *NewObjectRequest) GetObject() []byte {
	if m != nil {
		return m.Object
	}
	return nil
}

type NewObjectResponse struct {
	ID    []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *NewObjectResponse) Reset()                    { *m = NewObjectResponse{} }
func (m *NewObjectResponse) String() string            { return proto.CompactTextString(m) }
func (*NewObjectResponse) ProtoMessage()               {}
func (*NewObjectResponse) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{17} }

func (m *NewObjectResponse) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *NewObjectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type SBACMessage struct {
	Op       SBACOpcode       `protobuf:"varint,1,opt,name=op,proto3,enum=transactor.SBACOpcode" json:"op,omitempty"`
	Decision SBACDecision     `protobuf:"varint,2,opt,name=decision,proto3,enum=transactor.SBACDecision" json:"decision,omitempty"`
	Tx       *SBACTransaction `protobuf:"bytes,3,opt,name=tx" json:"tx,omitempty"`
	PeerID   uint64           `protobuf:"varint,4,opt,name=peerId,proto3" json:"peerId,omitempty"`
}

func (m *SBACMessage) Reset()                    { *m = SBACMessage{} }
func (m *SBACMessage) String() string            { return proto.CompactTextString(m) }
func (*SBACMessage) ProtoMessage()               {}
func (*SBACMessage) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{18} }

func (m *SBACMessage) GetOp() SBACOpcode {
	if m != nil {
		return m.Op
	}
	return SBACOpcode_CONSENSUS1
}

func (m *SBACMessage) GetDecision() SBACDecision {
	if m != nil {
		return m.Decision
	}
	return SBACDecision_ACCEPT
}

func (m *SBACMessage) GetTx() *SBACTransaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SBACMessage) GetPeerID() uint64 {
	if m != nil {
		return m.PeerID
	}
	return 0
}

type SBACMessageAck struct {
	LastID uint64 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
}

func (m *SBACMessageAck) Reset()                    { *m = SBACMessageAck{} }
func (m *SBACMessageAck) String() string            { return proto.CompactTextString(m) }
func (*SBACMessageAck) ProtoMessage()               {}
func (*SBACMessageAck) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{19} }

func (m *SBACMessageAck) GetLastID() uint64 {
	if m != nil {
		return m.LastID
	}
	return 0
}

type SBACTransaction struct {
	ID        []byte            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tx        *Transaction      `protobuf:"bytes,2,opt,name=tx" json:"tx,omitempty"`
	Evidences map[uint64][]byte `protobuf:"bytes,3,rep,name=evidences" json:"evidences,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Op        SBACOpcode        `protobuf:"varint,4,opt,name=op,proto3,enum=transactor.SBACOpcode" json:"op,omitempty"`
	Signature []byte            `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *SBACTransaction) Reset()                    { *m = SBACTransaction{} }
func (m *SBACTransaction) String() string            { return proto.CompactTextString(m) }
func (*SBACTransaction) ProtoMessage()               {}
func (*SBACTransaction) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{20} }

func (m *SBACTransaction) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *SBACTransaction) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SBACTransaction) GetEvidences() map[uint64][]byte {
	if m != nil {
		return m.Evidences
	}
	return nil
}

func (m *SBACTransaction) GetOp() SBACOpcode {
	if m != nil {
		return m.Op
	}
	return SBACOpcode_CONSENSUS1
}

func (m *SBACTransaction) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transactor.Transaction")
	proto.RegisterType((*Strings)(nil), "transactor.strings")
	proto.RegisterType((*Trace)(nil), "transactor.Trace")
	proto.RegisterType((*Object)(nil), "transactor.Object")
	proto.RegisterType((*CheckTransactionRequest)(nil), "transactor.CheckTransactionRequest")
	proto.RegisterType((*CheckTransactionResponse)(nil), "transactor.CheckTransactionResponse")
	proto.RegisterType((*AddTransactionRequest)(nil), "transactor.AddTransactionRequest")
	proto.RegisterType((*ObjectTraceIDPair)(nil), "transactor.ObjectTraceIDPair")
	proto.RegisterType((*ObjectList)(nil), "transactor.ObjectList")
	proto.RegisterType((*AddTransactionResponse)(nil), "transactor.AddTransactionResponse")
	proto.RegisterType((*StateReport)(nil), "transactor.StateReport")
	proto.RegisterType((*StatesReportResponse)(nil), "transactor.StatesReportResponse")
	proto.RegisterType((*QueryObjectRequest)(nil), "transactor.QueryObjectRequest")
	proto.RegisterType((*QueryObjectResponse)(nil), "transactor.QueryObjectResponse")
	proto.RegisterType((*DeleteObjectRequest)(nil), "transactor.DeleteObjectRequest")
	proto.RegisterType((*DeleteObjectResponse)(nil), "transactor.DeleteObjectResponse")
	proto.RegisterType((*NewObjectRequest)(nil), "transactor.NewObjectRequest")
	proto.RegisterType((*NewObjectResponse)(nil), "transactor.NewObjectResponse")
	proto.RegisterType((*SBACMessage)(nil), "transactor.SBACMessage")
	proto.RegisterType((*SBACMessageAck)(nil), "transactor.SBACMessageAck")
	proto.RegisterType((*SBACTransaction)(nil), "transactor.SBACTransaction")
	proto.RegisterEnum("transactor.Opcode", Opcode_name, Opcode_value)
	proto.RegisterEnum("transactor.ObjectStatus", ObjectStatus_name, ObjectStatus_value)
	proto.RegisterEnum("transactor.SBACOpcode", SBACOpcode_name, SBACOpcode_value)
	proto.RegisterEnum("transactor.SBACDecision", SBACDecision_name, SBACDecision_value)
}

func init() { proto.RegisterFile("transactor/types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 1289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdf, 0x72, 0xda, 0xc6,
	0x17, 0x36, 0x02, 0x84, 0x39, 0x10, 0x2c, 0xaf, 0x1d, 0x47, 0xe3, 0x5f, 0x7e, 0x75, 0x46, 0xd3,
	0xa6, 0x2e, 0x49, 0x71, 0x42, 0xdc, 0x99, 0x4c, 0xa7, 0x37, 0x20, 0x34, 0x63, 0x6a, 0x07, 0x9c,
	0x85, 0x24, 0xed, 0x55, 0x46, 0x16, 0x1b, 0xac, 0xda, 0x96, 0x54, 0xed, 0x92, 0xc6, 0x7d, 0x89,
	0xbe, 0x42, 0x5f, 0xa2, 0xd3, 0x9b, 0xde, 0xf6, 0xb6, 0x8f, 0xe0, 0x0b, 0x3f, 0x49, 0x67, 0xff,
	0x80, 0x24, 0x8c, 0xe3, 0x36, 0xe9, 0xdd, 0xee, 0xb7, 0xdf, 0xf9, 0xf6, 0xec, 0x77, 0x8e, 0x76,
	0x01, 0x36, 0x58, 0xec, 0x06, 0xd4, 0xf5, 0x58, 0x18, 0xef, 0xb0, 0xf3, 0x88, 0xd0, 0x46, 0x14,
	0x87, 0x2c, 0x44, 0x90, 0xe0, 0x9b, 0x5f, 0x8e, 0x7d, 0x76, 0x3c, 0x39, 0x6a, 0x78, 0xe1, 0xd9,
	0xce, 0x38, 0x1c, 0x87, 0x3b, 0x82, 0x72, 0x34, 0x79, 0x23, 0x66, 0x62, 0x22, 0x46, 0x32, 0xd4,
	0x7a, 0x0a, 0x95, 0xa1, 0x0a, 0xf6, 0xc3, 0x00, 0x7d, 0x01, 0x3a, 0x8b, 0x5d, 0x8f, 0x50, 0x33,
	0x77, 0x2f, 0xbf, 0x5d, 0x69, 0xae, 0x36, 0x12, 0xe9, 0xc6, 0x90, 0xaf, 0x60, 0x45, 0xb0, 0xfe,
	0x0f, 0x25, 0xca, 0x62, 0x3f, 0x18, 0x53, 0x84, 0xa0, 0x40, 0x59, 0x2c, 0x63, 0xca, 0x58, 0x8c,
	0xad, 0x3f, 0xf3, 0x50, 0x14, 0x01, 0xa8, 0x01, 0xe0, 0x85, 0x01, 0x8f, 0x62, 0xdd, 0x8e, 0x99,
	0xbb, 0x97, 0xdb, 0x2e, 0xb7, 0x6b, 0x97, 0x17, 0x5b, 0x60, 0xcf, 0x50, 0x9c, 0x62, 0xa0, 0xbb,
	0x50, 0x8e, 0xe2, 0xd0, 0x23, 0xa3, 0x49, 0x4c, 0x4c, 0x8d, 0xd3, 0x71, 0x02, 0xa0, 0x3a, 0x18,
	0x7e, 0x10, 0x4d, 0x58, 0xff, 0xe8, 0x07, 0xe2, 0x31, 0xba, 0x4f, 0xce, 0xa9, 0x99, 0xbf, 0x97,
	0xdf, 0xae, 0xe2, 0x2b, 0x38, 0x7a, 0x04, 0x6b, 0x02, 0xc3, 0xe4, 0x0d, 0x89, 0x49, 0xe0, 0x11,
	0x49, 0x2f, 0x08, 0xfa, 0xa2, 0x25, 0xf4, 0x29, 0xdc, 0x0a, 0x27, 0x2c, 0x91, 0x31, 0x8b, 0x82,
	0x9b, 0x05, 0xd1, 0x27, 0x00, 0x91, 0x1b, 0xbb, 0x67, 0x84, 0x91, 0x98, 0x9a, 0xba, 0xa0, 0xa4,
	0x10, 0x64, 0x42, 0x29, 0x26, 0x6c, 0x12, 0x07, 0xd4, 0x2c, 0x89, 0xc5, 0xe9, 0x14, 0x3d, 0x00,
	0xfd, 0xd4, 0x3d, 0x22, 0xa7, 0xd4, 0x5c, 0x16, 0xfe, 0xae, 0xa5, 0xfd, 0x55, 0x76, 0x62, 0x45,
	0x41, 0x5f, 0x41, 0x75, 0x44, 0x22, 0x12, 0x8c, 0x48, 0xe0, 0xf9, 0x84, 0x9a, 0xe5, 0xeb, 0x4a,
	0x92, 0xa1, 0x21, 0x0b, 0xaa, 0x69, 0x27, 0x4c, 0x10, 0x29, 0x64, 0x30, 0xb4, 0x0d, 0x2b, 0x73,
	0xc7, 0x37, 0x2b, 0x82, 0x36, 0x0f, 0x5b, 0x3f, 0x83, 0x2e, 0x83, 0xd0, 0x3a, 0x14, 0xdf, 0xba,
	0xa7, 0x13, 0x22, 0x4a, 0x58, 0xc5, 0x72, 0x82, 0x0c, 0xc8, 0x9f, 0x90, 0x73, 0x51, 0xa7, 0x2a,
	0xe6, 0x43, 0xf4, 0x08, 0x74, 0xca, 0x5c, 0x36, 0xe1, 0x75, 0xc9, 0x6d, 0xd7, 0x9a, 0x66, 0x3a,
	0x61, 0xa9, 0x35, 0x10, 0xeb, 0x58, 0xf1, 0xd0, 0xc6, 0xcc, 0x95, 0x82, 0xe8, 0x20, 0x35, 0xb3,
	0xda, 0x70, 0xc7, 0x3e, 0x26, 0xde, 0x49, 0xaa, 0x43, 0x31, 0xf9, 0x71, 0x42, 0x28, 0x43, 0x9f,
	0x83, 0xc6, 0xde, 0x89, 0x4c, 0x2a, 0xcd, 0x3b, 0x73, 0x8e, 0xcc, 0xb8, 0x1a, 0x7b, 0x67, 0xed,
	0x81, 0x79, 0x55, 0x83, 0x46, 0x61, 0x40, 0x09, 0xaa, 0x81, 0x16, 0x9e, 0x08, 0x91, 0x65, 0xac,
	0x85, 0x27, 0xbc, 0xf3, 0xa8, 0x3f, 0x0e, 0x5c, 0x36, 0xed, 0xbc, 0x2a, 0x4e, 0x00, 0xeb, 0xaf,
	0x1c, 0xdc, 0x6e, 0x8d, 0x46, 0x1f, 0x91, 0x0c, 0xea, 0x41, 0x99, 0xbc, 0xf5, 0x47, 0xd2, 0x70,
	0x4d, 0x94, 0xf3, 0x51, 0x9a, 0xbf, 0x50, 0xbe, 0xe1, 0x4c, 0x43, 0x9c, 0x80, 0xc5, 0xe7, 0x38,
	0x91, 0xd8, 0xfc, 0x06, 0x6a, 0xd9, 0xc5, 0x69, 0x39, 0x78, 0x2e, 0x05, 0x59, 0x8e, 0x59, 0xd9,
	0xb4, 0x54, 0xd9, 0xbe, 0xd6, 0x9e, 0xe6, 0xac, 0x63, 0x58, 0x95, 0xe5, 0x10, 0x5d, 0xd4, 0xed,
	0x1c, 0xba, 0x7e, 0x8c, 0x3e, 0x83, 0x12, 0x93, 0x53, 0x59, 0xe7, 0x76, 0xe5, 0xf2, 0x62, 0xab,
	0xa4, 0x18, 0x78, 0xba, 0x86, 0x1e, 0x42, 0x29, 0x54, 0xfd, 0x25, 0xcf, 0x81, 0xae, 0x56, 0x19,
	0x4f, 0x29, 0xd6, 0x2e, 0x80, 0x84, 0x0e, 0x7c, 0xca, 0xd0, 0x7d, 0x28, 0x9c, 0xfa, 0x94, 0xa9,
	0x2b, 0x66, 0x51, 0xa0, 0x58, 0xb7, 0x7e, 0xcf, 0xc1, 0xc6, 0xbc, 0x23, 0xaa, 0x72, 0xdd, 0x64,
	0x7b, 0xa9, 0xb2, 0xf3, 0x3e, 0x1b, 0x65, 0x90, 0x12, 0x57, 0x2e, 0x4e, 0xe3, 0x37, 0x31, 0x54,
	0xd3, 0x0b, 0x69, 0x07, 0xcb, 0xd2, 0xc1, 0x87, 0x69, 0x07, 0x2b, 0xcd, 0x8d, 0xab, 0x09, 0xf3,
	0x63, 0xa5, 0x9d, 0xfd, 0xad, 0x00, 0x15, 0xde, 0xe3, 0x04, 0x93, 0x28, 0x8c, 0x19, 0x6f, 0xf0,
	0x63, 0x97, 0x1e, 0x2b, 0x4f, 0x6f, 0x61, 0x35, 0x43, 0x2f, 0x61, 0xc5, 0x0b, 0xcf, 0xce, 0x7c,
	0xd6, 0x21, 0x9e, 0x4f, 0xfd, 0x30, 0x98, 0xba, 0xf9, 0x30, 0xbd, 0x47, 0x4a, 0xa9, 0x61, 0x67,
	0xe9, 0xf2, 0x2c, 0xf3, 0x22, 0x5c, 0x37, 0x3a, 0x76, 0x29, 0x79, 0x9c, 0xe8, 0xe6, 0xdf, 0xaf,
	0x7b, 0x98, 0xa5, 0x2b, 0xdd, 0x39, 0x91, 0x99, 0x6e, 0x33, 0xd1, 0x2d, 0xfc, 0x03, 0xdd, 0xe6,
	0x42, 0xdd, 0x04, 0xe5, 0x3d, 0xca, 0xaf, 0x02, 0x62, 0x16, 0x85, 0xeb, 0x72, 0xc2, 0x2f, 0x63,
	0x7e, 0xad, 0xf9, 0xc1, 0xd8, 0x79, 0x4b, 0x02, 0xc6, 0x6f, 0xda, 0xdc, 0x76, 0x11, 0x67, 0xc1,
	0xcd, 0x36, 0xac, 0x2f, 0x32, 0xe5, 0xa6, 0x2f, 0x61, 0x39, 0x55, 0x2f, 0xae, 0xb1, 0xc8, 0x80,
	0x0f, 0xd2, 0x68, 0x7e, 0xb8, 0x86, 0x75, 0x06, 0xeb, 0xc2, 0x3c, 0x2a, 0xdd, 0x9b, 0xb5, 0xfb,
	0x8e, 0xbc, 0x52, 0x67, 0xcf, 0xf2, 0x9d, 0x6b, 0xec, 0xc6, 0x8a, 0xc6, 0xad, 0x23, 0xc2, 0x9e,
	0x6e, 0xf0, 0x7c, 0x42, 0xd4, 0x56, 0x45, 0x9c, 0x05, 0xad, 0x26, 0xa0, 0xe7, 0x13, 0x12, 0x9f,
	0xab, 0xaf, 0x4e, 0xdd, 0x66, 0x77, 0xa1, 0x2c, 0xbf, 0x8d, 0x7d, 0x95, 0x76, 0x15, 0x27, 0x80,
	0xf5, 0x0a, 0xd6, 0x32, 0x31, 0x2a, 0xc3, 0x3a, 0xe8, 0x92, 0xa3, 0xae, 0xc1, 0x45, 0x5f, 0xb5,
	0x62, 0xf0, 0xf3, 0x93, 0x38, 0x0e, 0x63, 0xf5, 0xb8, 0xcb, 0x89, 0xf5, 0x04, 0xd6, 0x3a, 0xe4,
	0x94, 0x30, 0xf2, 0x6f, 0xb2, 0xf9, 0x0e, 0xd6, 0xb3, 0x41, 0xff, 0x59, 0x3a, 0x75, 0x30, 0x7a,
	0xe4, 0xa7, 0x6c, 0x2e, 0x1b, 0x19, 0xd5, 0xea, 0x54, 0xc1, 0x6a, 0xc1, 0x6a, 0x8a, 0xab, 0x52,
	0xd8, 0x00, 0xcd, 0x1f, 0xa9, 0x3b, 0x54, 0xbf, 0xbc, 0xd8, 0xd2, 0xba, 0x1d, 0xac, 0xf9, 0xa3,
	0x6b, 0xb6, 0xfb, 0x23, 0x07, 0x95, 0x41, 0xbb, 0x65, 0x3f, 0x23, 0x94, 0xba, 0x63, 0x82, 0xee,
	0x83, 0x16, 0x46, 0x22, 0xba, 0x96, 0xbd, 0x70, 0x38, 0xa9, 0x1f, 0x79, 0xe1, 0x88, 0x60, 0x2d,
	0x8c, 0xd0, 0x2e, 0x2c, 0x8f, 0x54, 0xbf, 0x09, 0xc1, 0xb9, 0xe7, 0x96, 0xb3, 0xa7, 0xfd, 0x88,
	0x67, 0x4c, 0xf4, 0x40, 0x3c, 0x58, 0x79, 0x61, 0xcd, 0xff, 0xe6, 0xf9, 0xf3, 0x8f, 0x96, 0x05,
	0x7a, 0x44, 0x48, 0xdc, 0x1d, 0x99, 0x05, 0xde, 0xc3, 0x6d, 0xb8, 0xbc, 0xd8, 0xd2, 0x0f, 0x39,
	0xd2, 0xc1, 0x6a, 0xc5, 0xda, 0x85, 0x5a, 0x2a, 0xfb, 0x96, 0x77, 0xc2, 0xa3, 0x4e, 0x5d, 0xca,
	0xba, 0xd2, 0x02, 0x15, 0x75, 0xc0, 0x91, 0x0e, 0x56, 0x2b, 0xd6, 0xaf, 0x1a, 0xac, 0xcc, 0xed,
	0x78, 0xad, 0x6d, 0xf2, 0x8d, 0xd5, 0x6e, 0x7e, 0x63, 0xf7, 0xd2, 0x6f, 0xac, 0xbc, 0xf5, 0xea,
	0xef, 0x39, 0xe2, 0xf5, 0xaf, 0xab, 0xaa, 0x41, 0xe1, 0xc6, 0x1a, 0x64, 0x7e, 0x36, 0x14, 0xe7,
	0x7e, 0x36, 0x7c, 0xdc, 0x1b, 0x5d, 0xff, 0x25, 0x07, 0xba, 0xdc, 0x0a, 0x55, 0xa0, 0xf4, 0xa2,
	0xb7, 0xdf, 0xeb, 0xbf, 0xea, 0x19, 0x4b, 0xe8, 0x36, 0xac, 0xda, 0x7b, 0x8e, 0xbd, 0xff, 0x7a,
	0x88, 0x5b, 0xbd, 0x41, 0xcb, 0x1e, 0x76, 0xfb, 0x3d, 0x23, 0x87, 0xd6, 0x60, 0xa5, 0xd5, 0xe9,
	0x64, 0x40, 0x0d, 0x19, 0x50, 0x7d, 0xfe, 0xc2, 0xc1, 0xdf, 0xbf, 0xee, 0xb7, 0xbf, 0x75, 0xec,
	0xa1, 0x91, 0x47, 0xab, 0x70, 0xcb, 0xc6, 0x4e, 0x6b, 0xe8, 0x4c, 0xa1, 0x02, 0x87, 0x3a, 0xce,
	0x81, 0x93, 0x40, 0x45, 0x04, 0xa0, 0x0f, 0x86, 0xad, 0xa1, 0x33, 0x30, 0x74, 0xb4, 0x0c, 0x05,
	0x7e, 0x6a, 0xa3, 0x54, 0xdf, 0x9d, 0xbe, 0x97, 0xf2, 0x47, 0x1c, 0x67, 0xf1, 0x9d, 0x5e, 0x3a,
	0xc6, 0x12, 0xaa, 0xc2, 0x72, 0xb7, 0xa7, 0x66, 0x39, 0xbe, 0x72, 0xd0, 0xb7, 0xf7, 0x9d, 0x8e,
	0xa1, 0xd5, 0xdf, 0x00, 0x24, 0xae, 0xa1, 0x1a, 0x80, 0xdd, 0xef, 0x0d, 0x9c, 0xde, 0xe0, 0xc5,
	0xe0, 0xb1, 0xb1, 0x94, 0x99, 0x37, 0x65, 0xe4, 0xe1, 0x5e, 0x6b, 0xe0, 0x3c, 0x36, 0xb4, 0xd9,
	0xb8, 0x69, 0xe4, 0xf9, 0xd8, 0xee, 0x3f, 0x7b, 0xd6, 0xe5, 0x09, 0xaf, 0x83, 0x31, 0x8b, 0x79,
	0xad, 0xd0, 0x62, 0xfd, 0x3e, 0x54, 0xd3, 0x3d, 0x2f, 0xb3, 0xb3, 0x9d, 0xc3, 0xa1, 0xb1, 0xc4,
	0xc7, 0xd8, 0x11, 0x67, 0xcb, 0x1d, 0xe9, 0xe2, 0xef, 0xcf, 0x93, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0xa6, 0x63, 0x77, 0x4a, 0x53, 0x0d, 0x00, 0x00,
}
