// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package transactor

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type OpCode int32

const (
	OpCode_UNKNOWN            OpCode = 0
	OpCode_TRANSACTION        OpCode = 1
	OpCode_QUERY              OpCode = 2
	OpCode_TRANSACTION_RESULT OpCode = 3
	OpCode_ERROR              OpCode = 100
)

var OpCode_name = map[int32]string{
	0:   "UNKNOWN",
	1:   "TRANSACTION",
	2:   "QUERY",
	3:   "TRANSACTION_RESULT",
	100: "ERROR",
}
var OpCode_value = map[string]int32{
	"UNKNOWN":            0,
	"TRANSACTION":        1,
	"QUERY":              2,
	"TRANSACTION_RESULT": 3,
	"ERROR":              100,
}

func (x OpCode) String() string {
	return proto.EnumName(OpCode_name, int32(x))
}
func (OpCode) EnumDescriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

type RawMessage struct {
	Op        OpCode `protobuf:"varint,1,opt,name=op,proto3,enum=transactor.OpCode" json:"op,omitempty"`
	Payload   []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *RawMessage) Reset()                    { *m = RawMessage{} }
func (m *RawMessage) String() string            { return proto.CompactTextString(m) }
func (*RawMessage) ProtoMessage()               {}
func (*RawMessage) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{0} }

func (m *RawMessage) GetOp() OpCode {
	if m != nil {
		return m.Op
	}
	return OpCode_UNKNOWN
}

func (m *RawMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *RawMessage) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// TODO: strings should be bytes, but for the purpose of simplicity (testing with json)
// now these are strings
type Object struct {
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *Object) Reset()                    { *m = Object{} }
func (m *Object) String() string            { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()               {}
func (*Object) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{1} }

func (m *Object) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Object) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type Transaction struct {
	Trace []*Trace `protobuf:"bytes,1,rep,name=trace" json:"trace,omitempty"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{2} }

func (m *Transaction) GetTrace() []*Trace {
	if m != nil {
		return m.Trace
	}
	return nil
}

// TODO: strings should be bytes (localParameters and localReturns), but for the purpose of
// simplicity (testing with json) now these are strings
type Trace struct {
	Contract        *Object   `protobuf:"bytes,1,opt,name=contract" json:"contract,omitempty"`
	Procedure       string    `protobuf:"bytes,2,opt,name=procedure,proto3" json:"procedure,omitempty"`
	InputObjects    []*Object `protobuf:"bytes,3,rep,name=inputObjects" json:"inputObjects,omitempty"`
	InputReference  []*Object `protobuf:"bytes,4,rep,name=inputReference" json:"inputReference,omitempty"`
	OutputObjects   []*Object `protobuf:"bytes,5,rep,name=outputObjects" json:"outputObjects,omitempty"`
	LocalParameters []string  `protobuf:"bytes,6,rep,name=localParameters" json:"localParameters,omitempty"`
	LocalReturns    []string  `protobuf:"bytes,7,rep,name=localReturns" json:"localReturns,omitempty"`
	Dep             []*Trace  `protobuf:"bytes,8,rep,name=dep" json:"dep,omitempty"`
}

func (m *Trace) Reset()                    { *m = Trace{} }
func (m *Trace) String() string            { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()               {}
func (*Trace) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{3} }

func (m *Trace) GetContract() *Object {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *Trace) GetProcedure() string {
	if m != nil {
		return m.Procedure
	}
	return ""
}

func (m *Trace) GetInputObjects() []*Object {
	if m != nil {
		return m.InputObjects
	}
	return nil
}

func (m *Trace) GetInputReference() []*Object {
	if m != nil {
		return m.InputReference
	}
	return nil
}

func (m *Trace) GetOutputObjects() []*Object {
	if m != nil {
		return m.OutputObjects
	}
	return nil
}

func (m *Trace) GetLocalParameters() []string {
	if m != nil {
		return m.LocalParameters
	}
	return nil
}

func (m *Trace) GetLocalReturns() []string {
	if m != nil {
		return m.LocalReturns
	}
	return nil
}

func (m *Trace) GetDep() []*Trace {
	if m != nil {
		return m.Dep
	}
	return nil
}

type TransactionResult struct {
	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (m *TransactionResult) Reset()                    { *m = TransactionResult{} }
func (m *TransactionResult) String() string            { return proto.CompactTextString(m) }
func (*TransactionResult) ProtoMessage()               {}
func (*TransactionResult) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{4} }

func (m *TransactionResult) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Query struct {
	Object *Object `protobuf:"bytes,1,opt,name=object" json:"object,omitempty"`
}

func (m *Query) Reset()                    { *m = Query{} }
func (m *Query) String() string            { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()               {}
func (*Query) Descriptor() ([]byte, []int) { return fileDescriptorTypes, []int{5} }

func (m *Query) GetObject() *Object {
	if m != nil {
		return m.Object
	}
	return nil
}

func init() {
	proto.RegisterType((*RawMessage)(nil), "transactor.RawMessage")
	proto.RegisterType((*Object)(nil), "transactor.Object")
	proto.RegisterType((*Transaction)(nil), "transactor.Transaction")
	proto.RegisterType((*Trace)(nil), "transactor.Trace")
	proto.RegisterType((*TransactionResult)(nil), "transactor.TransactionResult")
	proto.RegisterType((*Query)(nil), "transactor.Query")
	proto.RegisterEnum("transactor.OpCode", OpCode_name, OpCode_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptorTypes) }

var fileDescriptorTypes = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xcf, 0x6f, 0xd3, 0x4e,
	0x10, 0xc5, 0xbf, 0xb6, 0x6b, 0xa7, 0x1e, 0xe7, 0xdb, 0xba, 0x73, 0x40, 0x7b, 0xe0, 0x10, 0x99,
	0x43, 0xad, 0x1e, 0x7c, 0x68, 0xa5, 0x0a, 0x71, 0xab, 0xaa, 0x1c, 0x10, 0x60, 0xd3, 0xad, 0x23,
	0xc4, 0x09, 0x6d, 0xed, 0xa1, 0x09, 0x04, 0xef, 0x6a, 0x77, 0x2d, 0x94, 0x7f, 0x9c, 0x33, 0xf2,
	0xa6, 0x25, 0x3f, 0x44, 0xb8, 0xcd, 0xbe, 0xf7, 0x66, 0xe7, 0x63, 0x8f, 0x0d, 0x89, 0x5d, 0x29,
	0x32, 0x85, 0xd2, 0xd2, 0x4a, 0x04, 0xab, 0x45, 0x67, 0x44, 0x63, 0xa5, 0xce, 0xe6, 0x00, 0x5c,
	0xfc, 0xfc, 0x40, 0xc6, 0x88, 0x47, 0xc2, 0x0c, 0x7c, 0xa9, 0x98, 0x37, 0xf1, 0xf2, 0x93, 0x4b,
	0x2c, 0x36, 0xb1, 0xa2, 0x52, 0xb7, 0xb2, 0x25, 0xee, 0x4b, 0x85, 0x0c, 0x46, 0x4a, 0xac, 0x96,
	0x52, 0xb4, 0xcc, 0x9f, 0x78, 0xf9, 0x98, 0x3f, 0x1f, 0xf1, 0x25, 0xc4, 0x66, 0xf1, 0xd8, 0x09,
	0xdb, 0x6b, 0x62, 0x81, 0xf3, 0x36, 0x42, 0x56, 0x40, 0x54, 0x3d, 0x7c, 0xa3, 0xc6, 0x22, 0xc2,
	0x51, 0x2b, 0xac, 0x70, 0x73, 0x62, 0xee, 0x6a, 0x4c, 0x21, 0xf8, 0x4e, 0x2b, 0x77, 0x63, 0xcc,
	0x87, 0x32, 0xbb, 0x86, 0xa4, 0x7e, 0x02, 0x58, 0xc8, 0x0e, 0xcf, 0x21, 0xb4, 0x5a, 0x34, 0xc4,
	0xbc, 0x49, 0x90, 0x27, 0x97, 0x67, 0xdb, 0x74, 0xf5, 0x60, 0xf0, 0xb5, 0x9f, 0xfd, 0xf2, 0x21,
	0x74, 0x02, 0x16, 0x70, 0xdc, 0xc8, 0x6e, 0x50, 0xad, 0x9b, 0x95, 0xec, 0x3d, 0x93, 0xa3, 0xe1,
	0x7f, 0x32, 0x03, 0xbf, 0xd2, 0xb2, 0xa1, 0x76, 0xe0, 0x5f, 0x93, 0x6c, 0x04, 0xbc, 0x86, 0xf1,
	0xa2, 0x53, 0xbd, 0x5d, 0xb7, 0x19, 0x16, 0x38, 0x8e, 0xbf, 0xdd, 0xb8, 0x93, 0xc3, 0x37, 0x70,
	0xe2, 0xce, 0x9c, 0xbe, 0x92, 0xa6, 0xae, 0x21, 0x76, 0x74, 0xb0, 0x73, 0x2f, 0x89, 0xaf, 0xe1,
	0x7f, 0xd9, 0xdb, 0xad, 0xa1, 0xe1, 0xc1, 0xd6, 0xdd, 0x20, 0xe6, 0x70, 0xba, 0x94, 0x8d, 0x58,
	0x7e, 0x14, 0x5a, 0xfc, 0x20, 0x4b, 0xda, 0xb0, 0x68, 0x12, 0xe4, 0x31, 0xdf, 0x97, 0x31, 0x83,
	0xb1, 0x93, 0x38, 0xd9, 0x5e, 0x77, 0x86, 0x8d, 0x5c, 0x6c, 0x47, 0xc3, 0x57, 0x10, 0xb4, 0xa4,
	0xd8, 0xf1, 0xa1, 0x57, 0x3f, 0xb8, 0xd9, 0x39, 0x9c, 0x6d, 0x2d, 0x8c, 0x93, 0xe9, 0x97, 0x6e,
	0xd7, 0x73, 0x61, 0xe6, 0xcf, 0xbb, 0x1e, 0xea, 0xec, 0x0a, 0xc2, 0xbb, 0x9e, 0xf4, 0x0a, 0x2f,
	0x20, 0x92, 0x8e, 0xf7, 0x1f, 0xeb, 0x79, 0x4a, 0x5c, 0xd4, 0x10, 0xad, 0x3f, 0x42, 0x4c, 0x60,
	0x34, 0x2b, 0xdf, 0x95, 0xd5, 0xa7, 0x32, 0xfd, 0x0f, 0x4f, 0x21, 0xa9, 0xf9, 0x4d, 0x79, 0x7f,
	0x73, 0x5b, 0xbf, 0xad, 0xca, 0xd4, 0xc3, 0x18, 0xc2, 0xbb, 0xd9, 0x94, 0x7f, 0x4e, 0x7d, 0x7c,
	0x01, 0xb8, 0xe5, 0x7d, 0xe1, 0xd3, 0xfb, 0xd9, 0xfb, 0x3a, 0x0d, 0x86, 0xc8, 0x94, 0xf3, 0x8a,
	0xa7, 0xed, 0x43, 0xe4, 0xfe, 0x88, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x5c, 0x21,
	0xb4, 0x20, 0x03, 0x00, 0x00,
}
