// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import api "chainspace.io/prototype/checker/api"
import mock "github.com/stretchr/testify/mock"

// TransactionValidator is an autogenerated mock type for the TransactionValidator type
type TransactionValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: tx
func (_m *TransactionValidator) Validate(tx *api.Transaction) error {
	ret := _m.Called(tx)

	var r0 error
	if rf, ok := ret.Get(0).(func(*api.Transaction) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
